### ISSUE TITLE
gen:integer-in with lo = hi

### ISSUE THREAD

**Issue by yiyunliu** [Bogdanp/rackcheck#1]
The contract checks if hi > lo. I believe that's a mistake. According to the documentation: "A contract error is raised if lo is greater than hi", the correct check should be hi >= lo.

This behavior of `gen:integer-in` also affects `gen:frequency`; when `gen:frequency` has a single pair in the list, I will get a contract error from gen:integer-in (which I assume `gen:frequency` somehow depends on?).

**Comment by Bogdanp** [comment]
Thanks for the report! The contract was indeed wrong, as the range should be inclusive between the two arguments.
