### ISSUE TITLE
Modular package

### ISSUE THREAD

**Issue by lemastero** [Bogdanp/rackcheck#8]
Hi

Currently in [rackcheck package depends](https://pkgs.racket-lang.org/package/rackcheck) on scribble, racket-doc etc, because it is single package.

Would it be possible to make it more modular e.g. by splitting it into `rackcheck-lib` and `rackcheck` containing both rackcheck-lib and docs like [base64](https://pkgs.racket-lang.org/package/base64)?

Even more modular approach would be to have `rackcheck-lib`, `rackcheck-doc` and `rackcheck` like in [crypto](https://pkgs.racket-lang.org/package/crypto).

This would allow building faster & smaller docker images by using `rackcheck-lib`.

**Comment by Bogdanp** [comment]
Yes, splitting it into `rackheck-lib` and `rackcheck` would be fine by me. Let me know if you want to do that. If not, I'll probably get to it sometime in the next couple of weeks.

**Comment by lemastero** [comment]
Sure I can give it a shot.
